/**
 * Dynamic Service Definition Specification (DeployMind Core)
 *
 * Replaces hardcoded per-technology adapters with declarative, machine-readable,
 * versioned service definitions that can be dynamically generated by AI or loaded from catalog.
 */

export type ServiceCategory =
  | 'sql'
  | 'nosql'
  | 'cache'
  | 'broker'
  | 'graph'
  | 'vector'
  | 'search'
  | 'object_storage'
  | 'timeseries'
  | 'custom';

export type IsolationStrategy =
  | 'database_per_tenant'
  | 'vhost_or_namespace_per_tenant'
  | 'key_prefix_per_tenant'
  | 'bucket_per_tenant'
  | 'user_per_tenant'
  | 'dedicated_only';

export type WorkflowStepAction =
  | 'exec_in_container'
  | 'wait_for_health'
  | 'generate_credential';

export interface WorkflowStep {
  name: string;
  action: WorkflowStepAction;
  command?: string[]; // Tokenized command arguments executed inside container
  env?: Record<string, string>;
  ignoreFailure?: boolean;
}

export interface ServiceDefinition {
  id: string; // e.g. "def_clickhouse_24", "def_neo4j_5", "def_kafka_3"
  serviceType: string; // Canonical identifier, e.g. "clickhouse", "neo4j", "kafka"
  aliases: string[];
  category: ServiceCategory;
  version: string;
  image: string; // Official OCI image
  imageDigest?: string; // Resolved immutable manifest digest (sha256:...)
  defaultInternalPort: number;
  environment?: Record<string, string>;
  volumes?: Array<{
    nameSuffix: string;
    containerPath: string;
  }>;
  healthCheck: {
    type: 'exec' | 'http' | 'tcp';
    command?: string[];
    httpPath?: string;
    port?: number;
    timeoutSeconds?: number;
  };
  multiTenancy: {
    supported: boolean;
    isolationStrategy: IsolationStrategy;
    maxTenantsPerInstance?: number;
  };
  provisionWorkflow: WorkflowStep[];
  deprovisionWorkflow: WorkflowStep[];
  connectionContract: {
    uriTemplate?: string;
    envMappings: Record<string, string>;
  };
  securityPolicy: {
    disallowPrivileged: boolean;
    disallowHostMounts: boolean;
  };
  provenance: {
    source: 'builtin' | 'ai_generated' | 'operator_verified';
    evidenceSources?: string[];
    generatedAt: number;
  };
  status?: 'candidate' | 'approved' | 'rejected' | 'revoked';
  contentHash?: string;
}
