import type { RepoManifestSnapshot } from '../analyzer/repo.analyzer.js';

export class DockerfileSynthesizer {
  // Autonomously generates a production-ready, multi-stage Dockerfile
  // when a repository has NO Dockerfile or Compose file.
  synthesizeDockerfile(manifest: RepoManifestSnapshot): string {
    const runtime = manifest.primaryRuntime || 'node';

    switch (runtime) {
      case 'node':
        return this.synthesizeNodeDockerfile(manifest);
      case 'python':
        return this.synthesizePythonDockerfile(manifest);
      case 'go':
        return this.synthesizeGoDockerfile(manifest);
      case 'rust':
        return this.synthesizeRustDockerfile(manifest);
      default:
        return this.synthesizeGenericDockerfile(manifest);
    }
  }

  private synthesizeNodeDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 3000;

    return `# Autonomously generated by DeployMind
FROM node:22-bookworm-slim AS builder
WORKDIR /app
ENV CI=true
ENV CSC_IDENTITY_AUTO_DISCOVERY=false
ENV CODE_SIGN_IDENTITY="-"
ENV CODE_SIGNING_REQUIRED="NO"
ENV CODE_SIGNING_ALLOWED="NO"
COPY . .
RUN if [ -f pnpm-lock.yaml ]; then corepack enable && (pnpm install --frozen-lockfile || pnpm install); \\
    elif [ -f yarn.lock ]; then yarn install --frozen-lockfile || yarn install; \\
    elif [ -f package-lock.json ]; then npm ci || npm install; \\
    else npm install; fi
RUN if npm run | grep -q "build"; then npm run build || true; fi

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=${port}
ENV CI=true
ENV CSC_IDENTITY_AUTO_DISCOVERY=false
COPY --from=builder /app ./
EXPOSE ${port}
CMD ["sh", "-c", "if [ -f dist/index.html ]; then npx -y serve -s dist -l \${PORT} -p \${PORT}; elif [ -f build/index.html ]; then npx -y serve -s build -l \${PORT} -p \${PORT}; elif npm run | grep -q 'start'; then npm start; elif npm run | grep -q 'preview'; then npm run preview -- --host 0.0.0.0 --port \${PORT}; elif npm run | grep -q 'dev'; then npm run dev -- --host 0.0.0.0 --port \${PORT}; else node index.js; fi"]
`;
  }

  private synthesizePythonDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 8000;

    return `# Autonomously generated by DeployMind
FROM python:3.12-slim AS runner
WORKDIR /app
ENV PYTHONUNBUFFERED=1
ENV PORT=${port}
COPY requirements*.txt pyproject.toml* ./
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
COPY . .
EXPOSE ${port}
CMD ["python", "app.py"]
`;
  }

  private synthesizeGoDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 8080;

    return `# Autonomously generated by DeployMind
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/server .

FROM alpine:3.21 AS runner
WORKDIR /app
COPY --from=builder /app/server /app/server
EXPOSE ${port}
CMD ["/app/server"]
`;
  }

  private synthesizeRustDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 8080;

    return `# Autonomously generated by DeployMind
FROM rust:1.85-alpine AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock* ./
COPY src/ ./src/
RUN cargo build --release

FROM alpine:3.21 AS runner
WORKDIR /app
COPY --from=builder /app/target/release/* /app/server
EXPOSE ${port}
CMD ["/app/server"]
`;
  }

  private synthesizeGenericDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 3000;
    return `# Autonomously generated by DeployMind
FROM alpine:3.21
WORKDIR /app
COPY . .
EXPOSE ${port}
CMD ["sh", "-c", "echo 'Application started' && sleep infinity"]
`;
  }
}

export const dockerfileSynthesizer = new DockerfileSynthesizer();
