import type { RepoManifestSnapshot } from '../analyzer/repo.analyzer.js';

export class DockerfileSynthesizer {
  // Autonomously generates a production-ready, multi-stage Dockerfile
  // when a repository has NO Dockerfile or Compose file.
  synthesizeDockerfile(manifest: RepoManifestSnapshot): string {
    const runtime = manifest.primaryRuntime || 'node';

    switch (runtime) {
      case 'node':
        return this.synthesizeNodeDockerfile(manifest);
      case 'python':
        return this.synthesizePythonDockerfile(manifest);
      case 'go':
        return this.synthesizeGoDockerfile(manifest);
      case 'rust':
        return this.synthesizeRustDockerfile(manifest);
      default:
        return this.synthesizeGenericDockerfile(manifest);
    }
  }

  private synthesizeNodeDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 3000;

    return `# Autonomously generated by DeployMind
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json pnpm-lock.yaml* yarn.lock* ./
RUN if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \\
    elif [ -f yarn.lock ]; then yarn install --frozen-lockfile; \\
    elif [ -f package-lock.json ]; then npm ci; \\
    else npm install; fi
COPY . .
RUN if npm run | grep -q "build"; then npm run build; fi

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=${port}
COPY --from=builder /app ./
EXPOSE ${port}
USER node
CMD ["npm", "start"]
`;
  }

  private synthesizePythonDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 8000;

    return `# Autonomously generated by DeployMind
FROM python:3.12-slim AS runner
WORKDIR /app
ENV PYTHONUNBUFFERED=1
ENV PORT=${port}
COPY requirements*.txt pyproject.toml* ./
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
COPY . .
EXPOSE ${port}
CMD ["python", "app.py"]
`;
  }

  private synthesizeGoDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 8080;

    return `# Autonomously generated by DeployMind
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/server .

FROM alpine:3.21 AS runner
WORKDIR /app
COPY --from=builder /app/server /app/server
EXPOSE ${port}
CMD ["/app/server"]
`;
  }

  private synthesizeRustDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 8080;

    return `# Autonomously generated by DeployMind
FROM rust:1.85-alpine AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock* ./
COPY src/ ./src/
RUN cargo build --release

FROM alpine:3.21 AS runner
WORKDIR /app
COPY --from=builder /app/target/release/* /app/server
EXPOSE ${port}
CMD ["/app/server"]
`;
  }

  private synthesizeGenericDockerfile(manifest: RepoManifestSnapshot): string {
    const port = manifest.detectedPorts[0] || 3000;
    return `# Autonomously generated by DeployMind
FROM alpine:3.21
WORKDIR /app
COPY . .
EXPOSE ${port}
CMD ["sh", "-c", "echo 'Application started' && sleep infinity"]
`;
  }
}

export const dockerfileSynthesizer = new DockerfileSynthesizer();
